version: '3'

services:
  f2pool-exporter:
    build: .
    container_name: f2pool-exporter
    ports:
      - 5896:5896
    restart: unless-stopped
    command:
      - '--resources=bitcoin/youraccountname'
